global:
  resolve_timeout: 5m

route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'django-webhook'

receivers:
  - name: 'django-webhook'
    webhook_configs:
      - url: 'http://backend:8000/monitor/alert/webhook/'
        send_resolved: true 