global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'django'
    static_configs:
      - targets: ['backend:8000']
    metrics_path: '/metrics' 